version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - D:/coding/redis:/data
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge